<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RECAM.Common/RECAM.Common.csproj" />
    <ProjectReference Include="../RECAM.Models/RECAM.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="MongoDB.Driver" Version="2.30.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations/" />
    <Folder Include="Data/" />
  </ItemGroup>

</Project>
