<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RECAM.Common/RECAM.Common.csproj" />
    <ProjectReference Include="../RECAM.DataAccess/RECAM.DataAccess.csproj" />
    <ProjectReference Include="../RECAM.Models/RECAM.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces/" />
    <Folder Include="Repositories/" />
  </ItemGroup>

</Project>
