<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e861d41d-8bee-4027-8601-68ebf1d9840b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../RECAM.Common/RECAM.Common.csproj" />
    <ProjectReference Include="../RECAM.DataAccess/RECAM.DataAccess.csproj" />
    <ProjectReference Include="../RECAM.Service/RECAM.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers/" />
    <Folder Include="Middlewares/" />
  </ItemGroup>

</Project>
